### ISSUE TITLE
An issue!

### ISSUE THREAD

**Issue by yahmad** [gmph/limitless-temple#1]
Some issue body text.

**Comment by yahmad** [comment]
This has been fixed.

**Comment by yahmad** [comment]
Closing issue #doneit

**Comment by yahmad** [comment]
Oops it is still an issue!

**Comment by yahmad** [comment]
@gmph any more work needed?

**Comment by yahmad** [comment]
@yavi-team/developers this is an issue that you won't be interested in.

**Comment by gmph** [comment]
#2 is a bigger issue
